# Generated by Django 3.2.23 on 2023-11-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurfingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('max_capacity', models.IntegerField(default=10)),
                ('current_capacity', models.IntegerField(default=0)),
                ('class_type', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('surfing_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingSystem.surfingclass')),
            ],
        ),
    ]
