# Generated by Django 3.2.22 on 2023-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0004_booking_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='category',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Advance/Practicing', 'Advance/Practicing')], max_length=200, null=True),
        ),
    ]
