# Generated by Django 3.2.22 on 2023-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0005_alter_classes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='description',
            field=models.CharField(choices=[('Mix', 'Mix'), ('Female', 'Female'), ('Male', 'Male')], max_length=200, null=True),
        ),
    ]
