# Generated by Django 3.2.22 on 2023-12-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0006_alter_classes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingSystem.classes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookingSystem.customer'),
        ),
    ]
