# Generated by Django 3.2.23 on 2023-12-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0007_auto_20231204_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='tags',
            field=models.ManyToManyField(to='BookingSystem.Tag'),
        ),
    ]
