# Generated by Django 3.2.23 on 2023-12-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0008_auto_20231204_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tags',
        ),
        migrations.AddField(
            model_name='classes',
            name='tags',
            field=models.ManyToManyField(to='BookingSystem.Tag'),
        ),
    ]
